//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class studyingLiecense
    {
        public string id { get; set; }
        public int requestCode { get; set; }
        public string destinationCity { get; set; }
        public string liecenseDetails { get; set; }
        public string officeDestination { get; set; }
        public string studentExplanation { get; set; }
        public string liecenseCase1 { get; set; }
        public string liecenseCase2 { get; set; }
        public string liecenseCase3 { get; set; }
        public string liecenseCase4 { get; set; }
        public Nullable<System.DateTime> sendDate { get; set; }
        public string accepted { get; set; }
    
        public virtual student student { get; set; }
    }
}
